author: Jeff Caulfield
content_dir: _content
disqus: jeffcaulfield
ext: .html
google_analytics: UA-60208611-1
license:
  name: CC BY 4.0
  url: //creativecommons.org/licenses/by/4.0/
#media_dir: _assets
output_dir: .
pubkey:
  date: 2014-01-03
  fingerprint: 89D7 EA3A BA2C 318E B949  0859 8463 DC06 1FEF AD67
  id: 4096R/1FEFAD67
tagline: 'Caution: Abstraction Ahead'
template_dir: _template
url: //jeffcaulfield.com
