author: Jeff Caulfield
content_dir: content
disqus: jeffcaulfield
ext: .html
google_analytics: UA-60208611-1
license_name: CC BY 4.0
license_url: //creativecommons.org/licenses/by/4.0/
#media_dir: media
output_dir: .
pubkey_date: 2014-01-03
pubkey_fingerprint: 89D7 EA3A BA2C 318E B949  0859 8463 DC06 1FEF AD67
pubkey_id: 4096R/1FEFAD67
template_dir: template
url: //jeffcaulfield.com
